# Config file for the project
# Follows Li et al. (2020) "Scalable Gradients for Stochastic Differential Equations"

# Training parameters
sde:
  n_params : 2
  sde_type : 'stratonovich'
  params_sample_type : 'gaussian'
  noise_type : 'diagonal'
  t_span : [0, 10]
  t_size : 100

  drift : "-p[0] * x"
  diffusion : "p[1] * torch.ones_like(x) "

  fixed_params : [0.5, 0.5]

  method : "midpoint"
  fixed_noise : False


training:
  device : "cpu"
  n_iters : 10
  loss : "nn.MSELoss()"
  optimizer : "torch.optim.Adam(params, lr=lr)"
  lr : 0.02
  plot : True
  save : True
  save_path : "./code/img/"
